dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3
before_install:
        - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
install:
  - sudo apt-get install -qq libegl1-mesa
  - pip3 install -r requirements.txt
script:
  - py.test ./src/gui_testing.py

