sudo: required
dist: xenial
language: python
services:
  - xvfb
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
install:
  - sudo apt-get install -qq libegl1-mesa
  - pip3 install -r requirements.txt
  - "export DISPLAY=:99.0"
  - sleep 3
before_script:
  - "herbstluftwm &"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - py.test ./src/gui_testing.py








