dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3
install:
  - sudo apt-get install -qq libegl1-mesa
  - pip install -r requirements.txt
script:
  - python3 src/gui_main.py
